### ISSUE TITLE
Make checking for PHAPP_ENV variable optional.

### ISSUE THREAD

**Issue by rthideaway** [drunomics/phapp-cli#16]
There might be a case where you want to set PHAPP_ENV variable during php script execution dynamically. Currently phapp does not allow to execute init/update commands when there is no PHAPP_ENV set beforehand. Would be cool to allow something like `--no-phapp-env-check` to allow execution without any PHAPP_ENV set beforehand.

**Comment by fago** [comment]
I don't think that makes sense. Generally, phapp prepares the environment for script execution.

If at some point at your script execution you do not want to pass on the enviornment, you can do so anyway via  "env -i command".  So I don't think we need to introduce something here.

Other point is that the script and the php environment should match. But the script environment is currently not capable of handling logic as it was needed in php. So we might want to introduce some way to handle that logic in the script also - but that's another topic. 

So closing this as it's already possible via "env -i".
